_cmf_resource:
    pattern: /api/{repositoryName}/{path}
    requirements:
        path: .*
    defaults:
        _controller: cmf_resource_rest.controller.resource:resourceAction
        _format: json
